const List<String> categories = [
  'men',
  'women',
  'electronics',
  'accessories',
  'shoes',
  'home & garden',
  'beauty',
  'kids',
  'bags'
];

const Map<String, List<String>> subCategories = {
  'men': [
    'shirt',
    't-shirt',
    'jacket',
    'vest',
    'coat',
    'jeans',
    'shorts',
    'suit',
    'other',
  ],
  'women': [
    'dress',
    '2pcs sets',
    't-shirt',
    'top',
    'skirt',
    'jeans',
    'pants',
    'coat',
    'jacket',
    'other'
  ],
  'electronics': [
    'phone',
    'computer',
    'laptop',
    'smart tv',
    'phone holder',
    'charger',
    'usb cables',
    'head phone',
    'smart watch',
    'tablet',
    'mouse',
    'keyboard',
    'gaming',
    'other'
  ],
  'accessories': [
    'hat',
    'men sunglass',
    'w sunglass',
    'classic watch',
    'gloves',
    'belt waist',
    'ring',
    'necklace',
    'scarf set',
    'anklet',
    'other'
  ],
  'shoes': [
    'men slippers',
    'men classic',
    'men casual',
    'men boots',
    'men canvas',
    'men sport',
    'men snadals',
    'home slippers',
    'women slippers',
    'women boots',
    'women heels',
    'women sport',
    'women snadals',
    'other'
  ],
  'home & garden': [
    'living room',
    'bed room',
    'dinning room',
    'kitchen tools',
    'bath access.',
    'furniture',
    'decoration',
    'lighting',
    'garden',
    'other'
  ],
  'beauty': [
    'body care',
    'hair care',
    'men perfume',
    'women perfume',
    'make up',
    'other'
  ],
  'kids': [
    'girls sets',
    'girls dress',
    'girls top',
    'girls pants',
    'jacket',
    'sweatshirts',
    'boys sets',
    'boys top',
    'boys pants',
    'home wear',
    'boys suits',
    'baby shoes',
    'other'
  ],
  'bags': [
    'wallet',
    'clutch',
    'chest bag',
    'back pack',
    'business bags',
    'laptop bags',
    'women bags',
    'other'
  ],
};